"""Add project gradient columns

Revision ID: 81d724bb5cbb
Revises: b5ae2c000c2d
Create Date: 2026-09-04 15:56:38.357146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d724bb5cbb'
down_revision: Union[str, None] = 'b5ae2c000c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('gradient_from', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('gradient_to', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'gradient_to')
    op.drop_column('projects', 'gradient_from')
    # ### end Alembic commands ###
