"""Change hero_logo_urls to JSONB

Revision ID: b5ae2c000c2d
Revises: 51be872a911a
Create Date: 2026-08-06 22:56:54.523761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5ae2c000c2d'
down_revision: Union[str, None] = '51be872a911a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home_content', 'hero_logo_urls',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home_content', 'hero_logo_urls',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    # ### end Alembic commands ###
